### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by maxtimum** [maxtimum/CS351-Arduino#2]
*Serve & reciever indicator usual case
*Set counters
*Serve & reciever 10 - 10 single serve swapping

**Comment by DCouzijn** [comment]
*Winner of each set should be server for next set.

**Comment by DCouzijn** [comment]
*Serve & receiver change after decrement set score.

**Comment by DCouzijn** [comment]
LED light flashing on side of winning player regardless of SideSwap conditions.
